config/routes.rb
SampleApp::Application.routes.draw do

  resources :users 
  resources :users do 
    member do 
      get :followings, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :user_relationships, :only => [:create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'

end

app/views/shared/_button_follow.html.erb
<%= form_for( current_user.user_relationships.build(:followed_id => @user.id)) do |f| -%>
  <%= f.hidden_field :followed_id %>
  <div class="">
    <%= f.submit "Follow", :class => "btn btn-success" %>
  </div>
<% end -%>

app/views/shared/_button_unfollow.html.erb
<%= form_for current_user.user_relationships.find_by_followed_id(@user),
  :html => {:method => :delete } do |f| -%>
  <%= f.hidden_field :followed_id %>
  <div class="">
    <%= f.submit "Unfollow", :class => "btn" %>
  </div>
<% end -%>

app/views/shared/_feed_item.html.erb
<div class="row well" style="margin-left:0px;">
  <div class="span1">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </div>
  <div class="span6">
    <% if current_user?(feed_item.user) -%>
      <div class="tweet-action pull-right">
        <%= link_to "X", feed_item, :method => :delete, :confirm => "Sure?", :title => "Delete this post" %> 
      </div>
    <% end -%>
    <div class="tweet-user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </div>
    <div class="tweet-content">
      <%= feed_item.content %>
    </div>
    <div class="tweet-timestamp pull-right">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </div>
  </div>
</div>

app/views/shared/_user_stats.html.erb
<% @user ||= current_user %>
<div class="well">
  <ul>
    <li><strong>Name</strong>: <%= @user.name %></li>
    <li><strong>URL</strong>: <%= link_to user_url(@user), @user %></li>
    <li><strong>Tweet</strong>: <span id="stats-tweet"><%= @user.microposts.count %></span></li>
    <li>
      <strong>Follows</strong>: 
      <a href="<%= followings_user_path(@user) %>"><span id="stats-follows"><%= @user.followings.count %></span></a>
    </li>
    <li>
      <strong>Followed</strong>: 
      <a href="<%= followers_user_path(@user) %>"><span id="stats-followed"><%= @user.followers.count %></span></a>
    </li>
    </ul>
  </div>