config/routes.rb
SampleApp::Application.routes.draw do

  resources :users 
  resources :users do 
    member do 
      get :followings, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :user_relationships, :only => [:create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js"  %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="container">
    <div class="header row">
      <div class="span6">
        <h1><%= link_to 'Tameiki', root_path %></h1>
      </div>
      <div class="span6">
        <ul class="nav pull-right nav-pills">
          <% if signed_in? -%>
            <li><%= link_to "hi, " + current_user[:name], user_path(current_user)  %></li>
            <li><%= link_to content_tag(:i,'', :class => 'icon-asterisk') + " Users", users_path %></li>
            <li><%= link_to content_tag(:i,'', :class => 'icon-asterisk') + " Settings", edit_user_path(current_user) %></li>
            <li><%= link_to content_tag(:i,'', :class => 'icon-off') + " Logout", signout_path %></li>
          <% else %>
            <li><%= link_to content_tag(:i,'', :class => 'icon-home') + " Home", root_path  %></li>
            <li><%= link_to content_tag(:i,'', :class => 'icon-asterisk') + " About", about_path %></li>
            <li><%= link_to content_tag(:i,'', :class => 'icon-asterisk') + " Help", help_path %></li>
            <li><%= link_to content_tag(:i,'', :class => 'icon-off') + " Login", signin_path %></li>
          <% end -%>

        </ul>
      </div>
    </div><!-- /header -->
    <div class="section">
      <% if flash.any? -%>
        <% flash.each do |key ,value| -%>
          <div id="" class="flash alert alert-<%= key %>">
            <a href="#" id="" class="close">x</a> 
            <p><%= value %></p>
          </div>
        <% end -%>
      <% end -%>
      <%= yield %>
    </div><!-- /section -->
    <div class="footer">
      
      <div class="subnav">
        <ul class="nav nav-pills">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to content_tag(:i, '', :class => "icon-globe icon-white") + " Others", 'http://www.google.com/' %></li>
        </ul>
      </div>

    </div><!-- /footer -->

    <%= debug(params) if Rails.env.development? %>
    </div><!-- /container -->






</body>
</html>